
import React, { useEffect, useState } from 'react';
import { Wifi, WifiOff, Database, RotateCw, Download } from 'lucide-react';
import { getDatabaseStats } from '../lib/db';
import { getRemoteVersion, syncDatabase } from '../lib/sync';
import toast from 'react-hot-toast';

export const Footer: React.FC = () => {
    const [isOnline, setIsOnline] = useState(navigator.onLine);
    const [dbDate, setDbDate] = useState<string | null>(null);
    const [isSyncing, setIsSyncing] = useState(false);
    const [updateAvailable, setUpdateAvailable] = useState(false);

    useEffect(() => {
        const handleStatus = () => setIsOnline(navigator.onLine);
        window.addEventListener('online', handleStatus);
        window.addEventListener('offline', handleStatus);
        
        refreshStats();
        checkRemote();

        return () => {
            window.removeEventListener('online', handleStatus);
            window.removeEventListener('offline', handleStatus);
        };
    }, []);

    const refreshStats = async () => {
        const stats = await getDatabaseStats();
        if (stats && stats.last_updated) {
            // Timestamp is usually in ms if user uses Date.now().
            // distill.sql uses DuckDB. DuckDB epoch? 
            // In workflow we used $(date +%s%3N) which is ms.
            // In distill.sql we need to see what we inserted.
            // Actually, distill.sql didn't insert a timestamp into 'products' table row?
            // Wait, schema has last_updated INTEGER.
            // But distill.sql might not have populated it with a standard value?
            // Let's assume for now it might be 0 or populated.
            // If 0, we show "Basic".
            const date = new Date(Number(stats.last_updated));
            if (stats.last_updated > 0) {
                 setDbDate(date.toLocaleDateString());
            } else {
                 setDbDate("Basic");
            }
        } else {
             setDbDate("Empty");
        }
    };

    const checkRemote = async () => {
        if (!navigator.onLine) return;
        const remoteTs = await getRemoteVersion();
        const localVs = localStorage.getItem('db_version');
        
        // If remote exists AND (local is missing OR remote is newer)
        // Note: remoteTs is from version.json (generated by workflow).
        if (remoteTs && (!localVs || Number(localVs) < remoteTs)) {
            setUpdateAvailable(true);
        }
    }

    const handleSync = async () => {
        if (!isOnline) {
            toast.error("You are offline.");
            return;
        }
        setIsSyncing(true);
        const toastId = toast.loading("Connecting...");
        try {
            const updated = await syncDatabase((msg) => {
                 toast.loading(msg, { id: toastId });
            });
            if (updated) {
                toast.success("Database Updated!", { id: toastId });
                await refreshStats();
                setUpdateAvailable(false);
            } else {
                toast.success("Already up to date", { id: toastId });
            }
        } catch (e) {
            console.error(e);
            toast.error("Sync Failed", { id: toastId });
        } finally {
            setIsSyncing(false);
        }
    };

    return (
        <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200 px-4 py-2 flex items-center justify-between text-[10px] sm:text-xs text-slate-500 z-50 pb-[env(safe-area-inset-bottom)]">
            <div className="flex items-center gap-3">
                 <div className={`flex items-center gap-1.5 ${isOnline ? 'text-emerald-500' : 'text-slate-400'}`}>
                    {isOnline ? <Wifi size={14} /> : <WifiOff size={14} />}
                    <span className="font-semibold hidden sm:inline">{isOnline ? 'Online' : 'Offline'}</span>
                 </div>
                 
                 <div className="h-3 w-[1px] bg-slate-200"></div>

                 <div className="flex items-center gap-1.5">
                    <Database size={14} />
                    <span>{dbDate ? `${dbDate}` : 'No Data'}</span>
                 </div>
            </div>

            <button 
                onClick={handleSync}
                disabled={isSyncing}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full font-bold transition-all ${
                    updateAvailable 
                    ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md shadow-blue-200' 
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
            >
                {isSyncing ? (
                    <RotateCw size={14} className="animate-spin" />
                ) : updateAvailable ? (
                    <Download size={14} />
                ) : (
                    <RotateCw size={14} />
                )}
                {updateAvailable ? 'Update Available' : 'Sync Data'}
            </button>
        </div>
    );
};
